source 'https://cdn.cocoapods.org/'
inhibit_all_warnings!

platform :ios, '10.0'

target 'MoyaHandyJSON_Example' do
  pod 'MoyaHandyJSON/RxSwift', :path => '../'
  pod 'RxCocoa'
  pod 'RxDataSources'
end
